### ISSUE TITLE
couldnot install this plugin using zkg

### ISSUE THREAD

**Issue by manigsankar** [cisagov/icsnpp-ethercat#1]
Could you please help to find whats the issue here?
os: ubuntu20.04

The following packages will be INSTALLED:
  zeek/cisagov/icsnpp-ethercat (master)

Proceed? [Y/n] Installing "zeek/cisagov/icsnpp-ethercat"...
Failed installing "zeek/cisagov/icsnpp-ethercat": package build_command failed, see log in /opt/zeek/var/lib/zkg/logs/icsnpp-ethercat-build.log
error: incomplete installation, the follow packages failed to be installed:
  zeek/cisagov/icsnpp-ethercat (master)
The command '/bin/sh -c yes | zkg install icsnpp-ethercat' returned a non-zero code: 1

**Comment by Kleinspider** [comment]
We have added btest checking for installation of these parsers via ZKG which will hopefully catch any errors during installation. If you are still having trouble with the installation could you post the icsnpp-ethercat-build.log file that is generated so we could help assist?
